### ISSUE TITLE
Thunderbird 60 support

### ISSUE THREAD

**Issue by dlech** [kee-org/keebird#1]
It looks like there are going to need to be some changes made to this extension for TB 60 compatibility (technically >=57, but 60 is the next stable release).

> Dear Add-on Developer,
>
> As you might know, Thunderbird 60 will be released in May 2018. Thunderbird 60 Beta is currently available on the beta channel.
>
> Many things have changed in the Mozilla platform code on which Thunderbird and add-ons are based. We have compiled a comprehensive [list of changes](https://click.e.mozilla.org/?qs=9b84e6f69961c268c00b8fab0b350d9ea27543ec875557997cd23023a27510c3d8465cdb29e6b5a1c1770645ee8f2c4394fe56702a9ebc76). It is likely your add-on will require some changes to be compatible with Thunderbird 60. In many cases those changes are minor. We ask you to test your add-on with this version and fix any issues. Please contact the Thunderbird team as described [here](https://click.e.mozilla.org/?qs=9b84e6f69961c26847bb18a85d3ea90cea16d4250ffa5a129124ec4efb111b0d19d2975b0495f4e9121884f8f91943d98a9b1f693f0fd3f3) if you need support.
>
> If your add-on is still compatible without any changes, please visit addons.mozilla.org and mark it compatible. For your add-on(s), click on “Manage Status & Versions”, then under “Listed versions”, click the link for a version and adjust the versions it is compatible with.
>
> To protect users from malfunction of Thunderbird caused by incompatible add-ons, the Thunderbird team has decided to classify all add-ons which have not been marked compatible with Thunderbird 60 as incompatible. These add-ons will be disabled when a user upgrades to version 60. We appreciate your understanding and cooperation in this matter.
>
>Regards,
>
>The Thunderbird & Add-ons teams

**Comment by adnion** [comment]
+1 for TB60 support

**Comment by juxeii** [comment]
Any news on this? TB 60 is officially out.

**Comment by zlatovlas** [comment]
+1 for TB60 support

**Comment by dlech** [comment]
Release has been made. See https://github.com/kee-org/keebird/releases/tag/v1.1.0

I will push to the addons website shortly as well (although review could take some days).

Please open a new issue if anything has broken.

**Comment by invidian** [comment]
Great news, it seems to work flawlessly!
