### ISSUE TITLE
Passwords are not saved/fetched with KeeBird

### ISSUE THREAD

**Issue by Varstahl** [kee-org/keebird#10]
I gave it KeeBird & KeePassRPC a spin today, as I already use KeePass2 for everything else. After a bit of setup and secret sharing between Bird & RPC, nothing more happens. So far:

- accounts don't get saved when I create a new one in ThunderBird
- passwords don't get saved in the DB or anywhere else
- although there are manually saved email/password couples in the DB, I always get a "No matching password found" (or a similar message) when trying to access any account that doesn't have a password saved in the ThunderBird password manager.

I'll admit I never used KeeFox or KeePassRPC before, so if you have any pointers about what could I be doing wrong, if anything, would be appreciated. Afair after the handshake I've been asked whether to create a new db or use an existing one, I chose to use an existing one and then tried to use it with KeeBird. KeeBird stopped telling me I didn't have access to the DB, but it won't store/retrieve anything whatsoever in any way, shape or form.

**Edit**: Setting the home Kee group on KeePass didn't yield any effect.

—————
Win7 x64
KeePass 2.39.1
KeePassRPC 1.8.0.0
KeeBird 1.0.1

**Comment by dlech** [comment]
According to the wiki...

> Currently passwords must be manually setup in KeePass

https://github.com/kee-org/keebird/wiki#initial-setup

**Comment by Varstahl** [comment]
Thank you very much, I've read the README and googled it out, but I totally missed the Wiki.

Now, on to #8, then I'm golden :D
