### ISSUE TITLE
Publish keebird on thunderbird's addon website

### ISSUE THREAD

**Issue by WPFilmmaker** [kee-org/keebird#12]
At the moment keebird is not available there,which makes hard to find the addon and install it (actually I haven't figured out where the download is..) which is a big minus as many users download addons only from there. Can you add keebird to the website?

**Comment by dlech** [comment]
It is there: https://addons.mozilla.org/en-GB/thunderbird/addon/keebird

**Comment by WPFilmmaker** [comment]
I must have overlooked, thanks!
