### ISSUE TITLE
HTTP Authentication for WebDav does not load any passwords

### ISSUE THREAD

**Issue by zlatovlas** [kee-org/keebird#16]
Hello, 

firstly, I would like to thank you for KeeBird!

Everything works well, even with Thunderbird 60, apart from one thing - HTTP Authentication dialogue does not seem to load any passwords. However, it worked with previous versions. 

I believe there was a similar problem with some Thunderbird version (5x.xx).

Please see below.
![capture](https://user-images.githubusercontent.com/14950788/44056968-2209aaba-9f4a-11e8-9cc7-6d7d7c29a72a.PNG)

**Comment by stuehmer** [comment]
I see the same problem about KeeBird not being invoked for passwords (including the Thunderbird message `WARNING: You password will not be sent....`)

**Comment by kkapsner** [comment]
I see that KeeBird has an embedded WebExtension. I think with the webRequest-API you should be able to solve this issue: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest

**Comment by dlech** [comment]
https://github.com/kee-org/keebird/releases/tag/1.1.1

**Comment by kkapsner** [comment]
Version 1.1.1 does not solve the issue. Please reopen.

**Comment by dlech** [comment]
Let's try this again: https://github.com/kee-org/keebird/releases/tag/1.1.2

**Comment by kkapsner** [comment]
Still not working. Can I provide you with any information that can help you?

**Comment by dlech** [comment]
I don't have a way to reproduce the problem. If there is a server I could try to connect to that results in the message being shown, then I could really fix it instead of just guessing.

**Comment by kkapsner** [comment]
I my case it's a calendar from owncloud. Unfortunately the demo page does not have the calendar activated.
But I can create a simple calendar behind HTTP authentication that you can use for testing. I just have to set it up.

**Comment by crazy-max** [comment]
Still not working with KeeBird 1.1.2. (Thunderbird 60 + Nextcloud Calendar ; see #17)

**Comment by kkapsner** [comment]
https://projects.kkapsner.de/Kalender/Ferien-protected.ics.php
User test
Password test

**Comment by dlech** [comment]
I'm able to reproduce the problem now, but the DOM inspector and javascript debugger that I used to use no longer work in TB 60. :cry:

**Comment by dlech** [comment]
with a little help from `#maildev`, I am back in business. :smile:

**Comment by dlech** [comment]
Should be fixed for real this time: https://github.com/kee-org/keebird/releases/tag/1.1.3

**Comment by zlatovlas** [comment]
works like a charm! any way to donate?

**Comment by kkapsner** [comment]
Great. Thanks for the quick fix.

**Comment by dlech** [comment]
> any way to donate?

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=88PN37SRKLAEW
