### ISSUE TITLE
No matching entry found with Agenda since Thunderbird 60

### ISSUE THREAD

**Issue by crazy-max** [kee-org/keebird#17]
Hi,

Windows 10 64-bits
Keepass 2.39.1
Thunderbird 60.0
KeeBird 1.1.0

I can't make things work only with the Agenda prompt for login/password since Thunderbird 60
Maybe linked to kee-org/KeeFox#779 ?

Thanks

**Comment by darkelfe14728** [comment]
Same issue for me
![img-000373](https://user-images.githubusercontent.com/509102/45016806-16a5a380-b026-11e8-9756-55ea9ba90d56.png)

**Comment by dlech** [comment]
Duplicate of #16?

**Comment by dlech** [comment]
Please try: https://github.com/kee-org/keebird/releases/tag/1.1.1

**Comment by crazy-max** [comment]
@dlech Yep seems a duplicate of #16
