### ISSUE TITLE
Thunderbird 68 support

### ISSUE THREAD

**Issue by dlech** [kee-org/keebird#18]
It looks like some changes will be required for this (again):

https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63

**Comment by sergeevabc** [comment]
Indeed, Keebird does not work with Thunderbird Beta (which is 64 now).

**Comment by dlech** [comment]
I've started working on this.

A better description of the required changes is at: https://developer.thunderbird.net/add-ons/updates/tb68

One big-ish snag I have hit is that the message interface used by the logger has been removed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1448850

Another thing I haven't touched yet is fixing the preferences UI. [prefwindow and friends are removed](https://developer.thunderbird.net/add-ons/updates/tb68#less-than-prefwindow-greater-than-less-than-prefpane-greater-than-less-than-preferences-greater-than-and-less-than-preference-greater-than), so it is a bit of a chore to replace them. See [example from another extension](https://github.com/dlech/gmailbuttons/commit/139a3e33e031d61fec30b0602217bd5ccf3ce1ea).

If anyone is able to help with any of this, please reach out.

**Comment by jakstu** [comment]
Since Thunderbird 68 is stable and released everywhere now it would be nice if that issue could be solved. Thank you for your work.

**Comment by alie2n** [comment]
Thanks for all the work so far.

For now I rolled back some pcs, but any news on this would be nice. :)

**Comment by dlech** [comment]
Hopefully working version available for testing: https://github.com/kee-org/keebird/releases/tag/v2.0.0

Should also be available at https://addons.thunderbird.net/en-US/thunderbird/addon/keebird/ pending review.

If something is broken, please open a new issue with detailed information on how to reproduce the problem.

**Comment by ikenichiro** [comment]
v2.0.0 Downloaded from github, so far working as expected!
Thank you for all the work!!

**Comment by zlatovlas** [comment]
much appreciated!

**Comment by AcHub** [comment]
Any idea when the pending Thunderbird addon review will be finished?

**Comment by dlech** [comment]
> Queue Position: 8 of 21 

I think we started out at 10 or 11

**Comment by dlech** [comment]
Finally passed review. https://addons.thunderbird.net/en-US/thunderbird/addon/keebird/
