### ISSUE TITLE
Not working with Thunderbird 60.7.1 (64-Bit) / KeePassXC

### ISSUE THREAD

**Issue by GITMichaelK** [kee-org/keebird#20]
Just tried keebird with Thunderbird 60.7.1 (64-Bit) / KeePassXC on LINUX.
It is not working! keebird claims, that the KeePass Database is locked (which is not!) and the "Start KeePass" has no function.

**Comment by Varstahl** [comment]
afaik KeePassXC doesn't work and will never work with Keebird.
