### ISSUE TITLE
relative path issue with Thunderbird

### ISSUE THREAD

**Issue by eseb63** [kee-org/keebird#5]
hello,

i use for a long time the Liberkey and portable editions of Thunderbird and Keepass Professional Edition  
(currently Thunderbird 52.7, Keepass 2.39, Keebird 1.0.0 with KeepassRPC 1.8.0)

i have issues with relative path handling since Thunderbird 52.0.

- keebird doesn't launch keepass if a relative path is specified in the options (it works with an absolute one) ; these problems didn't occur with thunderbird 45.8 and older
- when clicking the browse button (for example keepass tab in the options) the specified relative path is ignored.
- the Keepass database when specified with a relative path is however well recognized 

Thunderbird exe Path : T:\LiberKey\Apps\Thunderbird\App\Thunderbird\thunderbird.exe
Keepass exe Path : T:\LiberKey\Apps\KeePassProfessionalEdition\App\KeePassProfessionalEdition\KeePass.exe

relative path in Keebird (Keepass tab) : ..\\..\\..\KeePassProfessionalEdition\App\KeePassProfessionalEdition
relative path in Keebird for Keepass database (advanced tab) : ..\\..\\..\KeePassProfessionalEdition\Data\KeePass.kdbx

thanks in advance for fixing

**Comment by dlech** [comment]
Please try https://github.com/kee-org/keebird/releases/tag/v1.0.1
