### ISSUE TITLE
Password remembering is broken

### ISSUE THREAD

**Issue by GregThib** [kee-org/keebird#6]
Hi,

I tried the plugin on Thunderbord, but for some reasons an OAuth connexion is asked at every Thunderbird launch. I could saw that the OAuth token is saved in the password engine of Thunderbird, but it seems ther is a problem for reading it.
So I de-installed your plugin for testing, and the situation is worse: now, I don't have the "remember this password" checkbox anymore.

Maybe the kee-bird plugin had "hooked" that event or something like that, and after a deletion the original hook is not restored ?
Anyway, do you have a simple process to restore the normal behaviour, if you think the problem come from KeeBird ?

Kind regards,
GT

**Comment by dlech** [comment]
1. Which version of Thunderbird are you using?

2. Can you be more specific about what type of account this OAuth is for?

3. The setting you are looking for is `signon.rememberSignons`. It can be changed in `about:config` (Preferences > Advanced > Config Editor...). It is supposed to be restored when you uninstall the extension.

**Comment by GregThib** [comment]
1. Latest version (master) : 52.8.0

2. That OAuth was for another plugin : gContactSync (bidirectional synchronisation w/ google Contacts)

3. Thanks a lot! I saw this param, but because my english is poor and my knowledge inexistant on Thunderbird configuration, I didn't wanted to change the value.

**So, your workaround work perfectly now.** And the OAuth too: it seems that it didn't be able to read the token value without the signon remember faculty. Weird, I know but hey, now it's work. Your plugin was probably not in cause in this particular problem.

I'll try later, with a proper installation of Thunderbird (less extension).

By the way, thank you very much @luckyrat and @dlech for your damn good tools and efforts (I use Keefox for years, now kee-agent). Really cool stuff.
