### ISSUE TITLE
keebird changes thunderbird window size

### ISSUE THREAD

**Issue by eseb63** [kee-org/keebird#8]
hello,
i didn't notice immediately but the v1.0.0 of keebird brings a new issue (it doesn't occur with keefox 1.7.2) :
i launch thunderbird in full screen mode ; when the connexion dialog appears, the thunderbird window isn't in full screen anymore but a bit larger. 
I have several accounts, so after each connexion, the thunderbird window becomes larger and larger..

thanks in advance for fixing

**Comment by dlech** [comment]
I know this information is in one of the other issues that you opened recently, but it would be helpful if you included Thunderbird version, OS, etc. in each issue so I don't have to go looking for it.

**Comment by Varstahl** [comment]
I freshly installed KeeBird and experience the same issue. As soon as the password field comes up, the main window is stripped of the maximized state and restored to movable window.

In my case; Win7 x64 latest Thunderbird x86 (52.8.0), and KeeBird (1.0.1).

**Comment by Varstahl** [comment]
Just a small update: I found out that on top of not being maximized anymore, for each subsequent password dialog popup, the window keeps getting larger and larger. By the end of my mail accounts list, the window grows about 120 pixels wider.

**Comment by dlech** [comment]
Fix released https://github.com/kee-org/keebird/releases/tag/v1.0.2
