### ISSUE TITLE
On Ubuntu 18.04 TB 52.8.0 Keebird 1.0.1 removes "use password manager" checkbox

### ISSUE THREAD

**Issue by g6094199** [kee-org/keebird#9]
Hi there!

i triied to use Keebird on TB 52. After remove the checkbox to enable "use password manager" is gone!
How to get it back?

![grafik](https://user-images.githubusercontent.com/37833326/40677097-f3101aa4-637c-11e8-8d8d-c4171277b339.png)

Sash

**Comment by dlech** [comment]
See #6

**Comment by g6094199** [comment]
it worked...thx
